# Generated by Django 3.0.7 on 2020-06-29 14:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0003_auto_20200629_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='calon',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
